[package]
name = "nos-common"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
ipnet = "2.9"
serde = { version = "1.0", features = ["derive"] }